[2024-05-04T13:01:06.369+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T13:01:06.393+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: for_project.upload_clean_to_gcs scheduled__2024-05-04T12:00:00+00:00 [queued]>
[2024-05-04T13:01:06.399+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: for_project.upload_clean_to_gcs scheduled__2024-05-04T12:00:00+00:00 [queued]>
[2024-05-04T13:01:06.400+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-04T13:01:06.415+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_clean_to_gcs> on 2024-05-04 12:00:00+00:00
[2024-05-04T13:01:06.426+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=101870) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T13:01:06.427+0000] {standard_task_runner.py:63} INFO - Started process 101907 to run task
[2024-05-04T13:01:06.426+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'for_project', 'upload_clean_to_gcs', 'scheduled__2024-05-04T12:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_project.py', '--cfg-path', '/tmp/tmph7kas_od']
[2024-05-04T13:01:06.428+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask upload_clean_to_gcs
[2024-05-04T13:01:06.480+0000] {task_command.py:426} INFO - Running <TaskInstance: for_project.upload_clean_to_gcs scheduled__2024-05-04T12:00:00+00:00 [running]> on host 5bc5768c5236
[2024-05-04T13:01:06.559+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='for_project' AIRFLOW_CTX_TASK_ID='upload_clean_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-04T12:00:00+00:00'
[2024-05-04T13:01:06.561+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T13:01:06.568+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-04T13:01:06.574+0000] {base.py:84} INFO - Using connection ID 'project_conn' for task execution.
[2024-05-04T13:01:06.574+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T13:01:06.574+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /opt/***/dags/data/all_data.csv
[2024-05-04T13:01:06.582+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=for_project, task_id=upload_clean_to_gcs, execution_date=20240504T120000, start_date=20240504T130106, end_date=20240504T130106
[2024-05-04T13:01:06.597+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task upload_clean_to_gcs (/opt/***/dags/data/all_data.csv; 101907)
[2024-05-04T13:01:06.608+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T13:01:06.626+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T13:01:06.635+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
