[2024-05-05T05:50:43.598+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T05:50:43.610+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.feed_to_bigq manual__2024-05-05T05:49:01.286722+00:00 [queued]>
[2024-05-05T05:50:43.617+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.feed_to_bigq manual__2024-05-05T05:49:01.286722+00:00 [queued]>
[2024-05-05T05:50:43.617+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-05T05:50:43.635+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): feed_to_bigq> on 2024-05-05 05:49:01.286722+00:00
[2024-05-05T05:50:43.647+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'feed_to_bigq', 'manual__2024-05-05T05:49:01.286722+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpyjihdtiw']
[2024-05-05T05:50:43.648+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask feed_to_bigq
[2024-05-05T05:50:43.652+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=51799) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T05:50:43.652+0000] {standard_task_runner.py:63} INFO - Started process 51806 to run task
[2024-05-05T05:50:43.714+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.feed_to_bigq manual__2024-05-05T05:49:01.286722+00:00 [running]> on host 5bc5768c5236
[2024-05-05T05:50:43.828+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='feed_to_bigq' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T05:49:01.286722+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T05:49:01.286722+00:00'
[2024-05-05T05:50:43.830+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T05:50:43.830+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T05:50:43.831+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 86, in _feed_to_bigq
    service_account_info = json.load(keyfile)
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'read'
[2024-05-05T05:50:43.843+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=feed_to_bigq, execution_date=20240505T054901, start_date=20240505T055043, end_date=20240505T055043
[2024-05-05T05:50:43.857+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 81 for task feed_to_bigq ('NoneType' object has no attribute 'read'; 51806)
[2024-05-05T05:50:43.870+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T05:50:43.890+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T05:50:43.899+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
