[2024-05-05T08:03:59.488+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T08:03:59.501+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.get_files manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T08:03:59.507+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.get_files manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T08:03:59.507+0000] {taskinstance.py:2303} INFO - Starting attempt 5 of 5
[2024-05-05T08:03:59.523+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_files> on 2024-05-05 06:09:12.404579+00:00
[2024-05-05T08:03:59.535+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'get_files', 'manual__2024-05-05T06:09:12.404579+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp6zpd8sbi']
[2024-05-05T08:03:59.537+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask get_files
[2024-05-05T08:03:59.539+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=13382) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T08:03:59.540+0000] {standard_task_runner.py:63} INFO - Started process 13384 to run task
[2024-05-05T08:03:59.578+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.get_files manual__2024-05-05T06:09:12.404579+00:00 [running]> on host 5bc5768c5236
[2024-05-05T08:03:59.683+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='get_files' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T06:09:12.404579+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T06:09:12.404579+00:00'
[2024-05-05T08:03:59.690+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T08:03:59.836+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1061 InsecureRequestWarning: Unverified HTTPS request is being made to host 'opendata.onde.go.th'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
[2024-05-05T08:04:03.429+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-05T08:04:03.430+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T08:04:03.441+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=sample, task_id=get_files, execution_date=20240505T060912, start_date=20240505T080359, end_date=20240505T080403
[2024-05-05T08:04:03.482+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-05T08:04:03.504+0000] {taskinstance.py:3482} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-05-05T08:04:03.510+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
