[2024-05-05T08:11:46.976+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T08:11:46.989+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.upload_clean_to_gcs manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T08:11:46.995+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.upload_clean_to_gcs manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T08:11:46.996+0000] {taskinstance.py:2303} INFO - Starting attempt 10 of 10
[2024-05-05T08:11:47.012+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_clean_to_gcs> on 2024-05-05 06:09:12.404579+00:00
[2024-05-05T08:11:47.022+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=17516) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T08:11:47.022+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'upload_clean_to_gcs', 'manual__2024-05-05T06:09:12.404579+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp95jzux45']
[2024-05-05T08:11:47.023+0000] {standard_task_runner.py:63} INFO - Started process 17518 to run task
[2024-05-05T08:11:47.024+0000] {standard_task_runner.py:91} INFO - Job 140: Subtask upload_clean_to_gcs
[2024-05-05T08:11:47.076+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.upload_clean_to_gcs manual__2024-05-05T06:09:12.404579+00:00 [running]> on host 5bc5768c5236
[2024-05-05T08:11:47.203+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='upload_clean_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T06:09:12.404579+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T06:09:12.404579+00:00'
[2024-05-05T08:11:47.207+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T08:11:47.218+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-05T08:11:47.224+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-05T08:11:47.225+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T08:11:47.225+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /opt/***/dags/data/cleaned/*.csv
[2024-05-05T08:11:47.235+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=upload_clean_to_gcs, execution_date=20240505T060912, start_date=20240505T081146, end_date=20240505T081147
[2024-05-05T08:11:47.252+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 140 for task upload_clean_to_gcs (/opt/***/dags/data/cleaned/*.csv; 17518)
[2024-05-05T08:11:47.287+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T08:11:47.305+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T08:11:47.315+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
