[2024-05-05T08:11:16.625+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T08:11:16.637+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.upload_clean_to_gcs manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T08:11:16.643+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.upload_clean_to_gcs manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T08:11:16.643+0000] {taskinstance.py:2303} INFO - Starting attempt 9 of 9
[2024-05-05T08:11:16.664+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_clean_to_gcs> on 2024-05-05 06:09:12.404579+00:00
[2024-05-05T08:11:16.676+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=17240) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T08:11:16.677+0000] {standard_task_runner.py:63} INFO - Started process 17242 to run task
[2024-05-05T08:11:16.681+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'upload_clean_to_gcs', 'manual__2024-05-05T06:09:12.404579+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpbe22_kf_']
[2024-05-05T08:11:16.682+0000] {standard_task_runner.py:91} INFO - Job 138: Subtask upload_clean_to_gcs
[2024-05-05T08:11:16.724+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.upload_clean_to_gcs manual__2024-05-05T06:09:12.404579+00:00 [running]> on host 5bc5768c5236
[2024-05-05T08:11:16.797+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='upload_clean_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T06:09:12.404579+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T06:09:12.404579+00:00'
[2024-05-05T08:11:16.798+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T08:11:16.804+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-05T08:11:16.809+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-05T08:11:16.810+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T08:11:16.810+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /opt/***/dags/data/cleaned/*.csv
[2024-05-05T08:11:16.817+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=upload_clean_to_gcs, execution_date=20240505T060912, start_date=20240505T081116, end_date=20240505T081116
[2024-05-05T08:11:16.830+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 138 for task upload_clean_to_gcs (/opt/***/dags/data/cleaned/*.csv; 17242)
[2024-05-05T08:11:16.853+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T08:11:16.874+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T08:11:16.884+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
