[2024-05-04T11:59:07.545+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T11:59:07.564+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.clean_df manual__2024-05-04T11:58:57.937589+00:00 [queued]>
[2024-05-04T11:59:07.572+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.clean_df manual__2024-05-04T11:58:57.937589+00:00 [queued]>
[2024-05-04T11:59:07.572+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-04T11:59:07.592+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): clean_df> on 2024-05-04 11:58:57.937589+00:00
[2024-05-04T11:59:07.608+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=68872) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T11:59:07.609+0000] {standard_task_runner.py:63} INFO - Started process 68876 to run task
[2024-05-04T11:59:07.613+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'clean_df', 'manual__2024-05-04T11:58:57.937589+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpf5ukf4hk']
[2024-05-04T11:59:07.616+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask clean_df
[2024-05-04T11:59:07.689+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.clean_df manual__2024-05-04T11:58:57.937589+00:00 [running]> on host 5bc5768c5236
[2024-05-04T11:59:08.044+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='clean_df' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T11:58:57.937589+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-04T11:58:57.937589+00:00'
[2024-05-04T11:59:08.045+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T11:59:08.046+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T11:59:08.046+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 65, in _clean_df
    df_all = pd.DataFrame(columns = column_names)
             ^^
NameError: name 'pd' is not defined
[2024-05-04T11:59:08.056+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=clean_df, execution_date=20240504T115857, start_date=20240504T115907, end_date=20240504T115908
[2024-05-04T11:59:08.071+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task clean_df (name 'pd' is not defined; 68876)
[2024-05-04T11:59:08.123+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T11:59:08.325+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T11:59:08.338+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
