[2024-05-04T12:00:05.838+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T12:00:05.852+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.clean_df manual__2024-05-04T11:58:57.937589+00:00 [queued]>
[2024-05-04T12:00:05.858+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.clean_df manual__2024-05-04T11:58:57.937589+00:00 [queued]>
[2024-05-04T12:00:05.858+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-04T12:00:05.875+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): clean_df> on 2024-05-04 11:58:57.937589+00:00
[2024-05-04T12:00:05.893+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'clean_df', 'manual__2024-05-04T11:58:57.937589+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp9vpwlikf']
[2024-05-04T12:00:05.895+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask clean_df
[2024-05-04T12:00:05.890+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=69352) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T12:00:05.897+0000] {standard_task_runner.py:63} INFO - Started process 69364 to run task
[2024-05-04T12:00:05.969+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.clean_df manual__2024-05-04T11:58:57.937589+00:00 [running]> on host 5bc5768c5236
[2024-05-04T12:00:06.142+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='clean_df' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T11:58:57.937589+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-04T11:58:57.937589+00:00'
[2024-05-04T12:00:06.144+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T12:00:06.184+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T12:00:06.185+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 67, in _clean_df
    for name in file_name:
                ^^^^^^^^^
NameError: name 'file_name' is not defined
[2024-05-04T12:00:06.203+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=clean_df, execution_date=20240504T115857, start_date=20240504T120005, end_date=20240504T120006
[2024-05-04T12:00:06.228+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task clean_df (name 'file_name' is not defined; 69364)
[2024-05-04T12:00:06.271+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T12:00:06.309+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T12:00:06.328+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
