[2024-05-05T07:52:59.305+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T07:52:59.317+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.gcs_to_bq_station manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T07:52:59.323+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.gcs_to_bq_station manual__2024-05-05T06:09:12.404579+00:00 [queued]>
[2024-05-05T07:52:59.324+0000] {taskinstance.py:2303} INFO - Starting attempt 11 of 11
[2024-05-05T07:52:59.339+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): gcs_to_bq_station> on 2024-05-05 06:09:12.404579+00:00
[2024-05-05T07:52:59.349+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'gcs_to_bq_station', 'manual__2024-05-05T06:09:12.404579+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpugf1poca']
[2024-05-05T07:52:59.350+0000] {standard_task_runner.py:91} INFO - Job 120: Subtask gcs_to_bq_station
[2024-05-05T07:52:59.354+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7380) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T07:52:59.355+0000] {standard_task_runner.py:63} INFO - Started process 7387 to run task
[2024-05-05T07:52:59.395+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.gcs_to_bq_station manual__2024-05-05T06:09:12.404579+00:00 [running]> on host 5bc5768c5236
[2024-05-05T07:52:59.486+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='gcs_to_bq_station' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T06:09:12.404579+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T06:09:12.404579+00:00'
[2024-05-05T07:52:59.487+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T07:52:59.495+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-05T07:52:59.499+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-05T07:52:59.500+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-05-05T07:52:59.545+0000] {bigquery.py:2328} INFO - Project is not included in destination_project_dataset_table: pm25.station; using project "upbeat-task-421414"
[2024-05-05T07:52:59.546+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'upbeat-task-421414', 'datasetId': 'pm25', 'tableId': 'station'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://dw-projec-swu-ds525/pm25_cleaned/*.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'station_id', 'type': 'STRING'}, {'name': 'name_th', 'type': 'STRING'}, {'name': 'name_en', 'type': 'STRING'}, {'name': 'area_th', 'type': 'STRING'}, {'name': 'area_en', 'type': 'STRING'}, {'name': 'province', 'type': 'STRING'}, {'name': 'station_type', 'type': 'STRING'}, {'name': 'lat', 'type': 'FLOAT'}, {'name': 'long', 'type': 'FLOAT'}, {'name': 'date', 'type': 'STRING'}, {'name': 'time', 'type': 'STRING'}, {'name': 'pm25_value', 'type': 'FLOAT'}, {'name': 'datetime', 'type': 'DATETIME'}]}, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-05-05T07:52:59.547+0000] {bigquery.py:1613} INFO - Inserting job ***_sample_gcs_to_bq_station_2024_05_05T06_09_12_404579_00_00_b8f36e64b0e5c3208111759fb51d8612
[2024-05-05T07:53:00.572+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T07:53:00.572+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 444, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Duplicate column 'Province' for table 'station_153b8385_3fcd_4348_ad98_5668e50f094a_source'. ; reason: invalidQuery, location: query, message: Duplicate column 'Province' for table 'station_153b8385_3fcd_4348_ad98_5668e50f094a_source'. 
[2024-05-05T07:53:00.581+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=gcs_to_bq_station, execution_date=20240505T060912, start_date=20240505T075259, end_date=20240505T075300
[2024-05-05T07:53:00.595+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 120 for task gcs_to_bq_station (400 Duplicate column 'Province' for table 'station_153b8385_3fcd_4348_ad98_5668e50f094a_source'. ; reason: invalidQuery, location: query, message: Duplicate column 'Province' for table 'station_153b8385_3fcd_4348_ad98_5668e50f094a_source'. ; 7387)
[2024-05-05T07:53:00.611+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T07:53:00.638+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T07:53:00.649+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
